#Using Script inspired by RafalSladek
#https://gist.github.com/RafalSladek/0d92fa68cb985c698560
image: node:latest

cache:
  untracked: true
  paths:
   - node_modules/

after_script:
  - gulp clean

# Build #
install_node_modules:
  stage: build
  script:
    # install runners
    - npm install --quiet -g gulp
    # install test software
    # - npm install --silent -g karma karma-mocha mocha karma-phantomjs-launcher phantomjs-prebuilt
    # install everything else
    - npm install --quiet


# Testing #
lint_js:
  stage: test
  script:
    - gulp vet-js

lint_ts:
  stage: test
  script:
    - gulp vet-ts

lint_html:
  stage: test
  script:
    - gulp vet-html

lint_less:
  stage: test
  script:
    - gulp vet-less

# test_app:
#   stage: test
#   script:
#     - gulp karma
# End Testing #

# Deployment #
deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to prod server"
  environment:
    name: Production
    url: https://grnfanzone.firebaseio.com/
  only:
  - master
# End Deployment #
