#Using Script inspired by RafalSladek
#https://gist.github.com/RafalSladek/0d92fa68cb985c698560
image: node:latest

cache:
  paths:
   - node_modules/

before_script:
  - npm install

after_script:
  - gulp clean

lint_app:
  stage: test
  script:
    - gulp vet

#To be changed to mocha once tests are actually set up
test_app:
  stage: test
  script:
    - gulp karma

#build_app:
#  only:
#    - master
#    - dev
#  script:
#    - gulp build
#


