#Using Script inspired by RafalSladek
#https://gist.github.com/RafalSladek/0d92fa68cb985c698560
image: node:latest

cache:
  paths:
   - node_modules/

before_script:
  # Global runner commands
  - npm install -g gulp firebase-tools angular-cli
  # Global tests software
  # - npm install --quiet -g karma karma-mocha mocha karma-phantomjs-launcher phantomjs-prebuilt
  # Install modules
  - npm install

after_script:
  - gulp clean

# Testing #
lint_src:
  stage: test
  except:
    - dev
    - master
  script:
    - gulp vet-html
    - gulp vet-js
    - gulp vet-json
    - gulp vet-css
    - gulp vet-less
    - gulp vet-ts
    - ng lint
    - gulp vet-fail


test_src:
  stage: test
  except:
    - dev
    - master
  script:
    - ng test --code-coverage --single-run
    - cat ./coverage/summary.txt
# End Testing #

# Deployment #
deploy_staging:
  stage: deploy
  environment: Staging
  only:
    - dev
  script:
    - firebase use --add grnfanzone-staging staging
    - firebase use --token $FIREBASE_TOKEN grnfanzone-staging staging
    - ng build -dev
    - firebase deploy --only hosting -m "[Staging] Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN


deploy_production:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - firebase use --add grnfanzone production
    - firebase use --token $FIREBASE_TOKEN grnfanzone production
    - ng build -prod
    - firebase deploy --only hosting -m "[Production] Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN
# End Deployment #
