#Using Script inspired by RafalSladek
#https://gist.github.com/RafalSladek/0d92fa68cb985c698560
image: node:latest

cache:
  paths:
   - node_modules/
   - bower_components/

before_script:
  # install runners
  - npm install --quiet -g bower gulp firebase-tools
  # install test software
  - npm install --quiet -g karma karma-mocha mocha karma-phantomjs-launcher phantomjs-prebuilt
  # install everything else
  - npm install --quiet
  # Bower components
  - bower install --allow-root

after_script:
  - gulp clean

# Testing #
lint_js:
  stage: test
  script:
    - gulp vet-js

lint_ts:
  stage: test
  script:
    - gulp vet-ts

lint_html:
  stage: test
  script:
    - gulp vet-html

lint_less:
  stage: test
  script:
    - gulp vet-less

# test_app:
#   stage: test
#   script:
#     - gulp karma
# End Testing #

# Deployment #
deploy_production:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - firebase use --add grnfanzone production
    - firebase use --token $FIREBASE_TOKEN production
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN
# End Deployment #
