#Using Script inspired by RafalSladek
#https://gist.github.com/RafalSladek/0d92fa68cb985c698560
image: node:latest

cache:
  paths:
   - node_modules/
   - bower_components/

before_script:
  - npm install
  - npm -i -g bower gulp
  - bower install

after_script:
  - gulp clean

#lint_app:
#  stage: test
#  script:
#    - gulp vet

#To be changed to mocha once tests are actually set up
test_app:
  stage: test
  script:
    - gulp vet
    - gulp karma



deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to prod server"
  environment:
    name: Production
    url: https://grnfanzone.firebaseio.com/
  only:
  - master


