#Using Script inspired by RafalSladek
#https://gist.github.com/RafalSladek/0d92fa68cb985c698560
image: node:latest

cache:
  paths:
   - node_modules/
   - bower_components/

before_script:
  - npm install
  # install runners
  - npm install -g bower gulp
  # install test software
  - npm install -g karma karma-mocha mocha karma-phantomjs-launcher
  - bower install --allow-root

after_script:
  - gulp clean

# Testing #
lint_app:
  stage: test
  script:
    - gulp vet

test_app:
  stage: test
  script:
    - gulp karma
# End Testing #

# Deployment #
deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to prod server"
  environment:
    name: Production
    url: https://grnfanzone.firebaseio.com/
  only:
  - master
# End Deployment #
