#Using Script inspired by RafalSladek
#https://gist.github.com/RafalSladek/0d92fa68cb985c698560
image: docker:latest

cache:
  paths:
   - node_modules/

before_script:
  - npm install
  - pwd
  - which gulp

after_script:
  - gulp clean

lint_app:
  stage: test
  script:
    - gulp vet

#To be changed to mocha once tests are actually set up
test_app:
  stage: test
  script:
    - gulp karma


deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to prod server"
  environment:
    name: Production
    url: https://grnfanzone.firebaseio.com/
  only:
  - master


