#Using Script inspired by RafalSladek
#https://gist.github.com/RafalSladek/0d92fa68cb985c698560
image: node:latest

cache:
  paths:
   - node_modules/
   - bower_components/

before_script:
  # install runners
  - npm install --quiet -g bower gulp
  # install test software
  - npm install --quiet -g karma karma-mocha mocha karma-phantomjs-launcher phantomjs-prebuilt
  # install everything else
  - npm install --quiet
  # Bower components
  - bower install --allow-root

after_script:
  - gulp clean

# Testing #
lint_js:
  stage: test
  script:
    - gulp vet-js

lint_ts:
  stage: test
  script:
    - gulp vet-ts

lint_html:
  stage: test
  script:
    - gulp vet-html


# test_app:
#   stage: test
#   script:
#     - gulp karma
# End Testing #

# Deployment #
deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to prod server"
  environment:
    name: Production
    url: https://grnfanzone.firebaseio.com/
  only:
  - master
# End Deployment #
