#Using Script inspired by RafalSladek
#https://gist.github.com/RafalSladek/0d92fa68cb985c698560
image: node:latest

cache:
  paths:
   - node_modules/

before_script:
  # Global runner commands
  - npm install -g gulp firebase-tools angular-cli
  # Global tests software
  # - npm install --quiet -g karma karma-mocha mocha karma-phantomjs-launcher phantomjs-prebuilt
  # Install modules
  - npm install

after_script:
  - gulp clean

# Testing #
lint_js:
  stage: test
  script:
    - gulp vet-js

lint_ts:
  stage: test
  script:
    - gulp vet-ts

lint_html:
  stage: test
  script:
    - gulp vet-html

lint_less:
  stage: test
  script:
    - gulp vet-less

test_src:
  stage: test
  script:
    - ng test --code-coverage --single-run

# test_app:
#   stage: test
#   script:
#     - gulp karma
# End Testing #

# Deployment #
deploy_production:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - firebase use --add grnfanzone production
    - firebase use --token $FIREBASE_TOKEN grnfanzone production
    - ng build --prod
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN
# End Deployment #
